/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Application deployment profile request payload
 */
@Schema(description = "Application deployment profile request payload")


public class V1AppDeploymentProfileEntity {
  @SerializedName("appProfileUid")
  private String appProfileUid = null;

  public V1AppDeploymentProfileEntity appProfileUid(String appProfileUid) {
    this.appProfileUid = appProfileUid;
    return this;
  }

   /**
   * Application deployment profile uid
   * @return appProfileUid
  **/
  @Schema(required = true, description = "Application deployment profile uid")
  public String getAppProfileUid() {
    return appProfileUid;
  }

  public void setAppProfileUid(String appProfileUid) {
    this.appProfileUid = appProfileUid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AppDeploymentProfileEntity v1AppDeploymentProfileEntity = (V1AppDeploymentProfileEntity) o;
    return Objects.equals(this.appProfileUid, v1AppDeploymentProfileEntity.appProfileUid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appProfileUid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AppDeploymentProfileEntity {\n");
    
    sb.append("    appProfileUid: ").append(toIndentedString(appProfileUid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
