/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1AppDeploymentSummary;
import com.spectrocloud.client.model.V1ListMetaData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1AppDeploymentsSummary
 */



public class V1AppDeploymentsSummary {
  @SerializedName("appDeployments")
  private List<V1AppDeploymentSummary> appDeployments = null;

  @SerializedName("listmeta")
  private V1ListMetaData listmeta = null;

  public V1AppDeploymentsSummary appDeployments(List<V1AppDeploymentSummary> appDeployments) {
    this.appDeployments = appDeployments;
    return this;
  }

  public V1AppDeploymentsSummary addAppDeploymentsItem(V1AppDeploymentSummary appDeploymentsItem) {
    if (this.appDeployments == null) {
      this.appDeployments = new ArrayList<V1AppDeploymentSummary>();
    }
    this.appDeployments.add(appDeploymentsItem);
    return this;
  }

   /**
   * Get appDeployments
   * @return appDeployments
  **/
  @Schema(description = "")
  public List<V1AppDeploymentSummary> getAppDeployments() {
    return appDeployments;
  }

  public void setAppDeployments(List<V1AppDeploymentSummary> appDeployments) {
    this.appDeployments = appDeployments;
  }

  public V1AppDeploymentsSummary listmeta(V1ListMetaData listmeta) {
    this.listmeta = listmeta;
    return this;
  }

   /**
   * Get listmeta
   * @return listmeta
  **/
  @Schema(description = "")
  public V1ListMetaData getListmeta() {
    return listmeta;
  }

  public void setListmeta(V1ListMetaData listmeta) {
    this.listmeta = listmeta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AppDeploymentsSummary v1AppDeploymentsSummary = (V1AppDeploymentsSummary) o;
    return Objects.equals(this.appDeployments, v1AppDeploymentsSummary.appDeployments) &&
        Objects.equals(this.listmeta, v1AppDeploymentsSummary.listmeta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appDeployments, listmeta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AppDeploymentsSummary {\n");
    
    sb.append("    appDeployments: ").append(toIndentedString(appDeployments)).append("\n");
    sb.append("    listmeta: ").append(toIndentedString(listmeta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
