/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1AppProfileMetadata;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1AppProfilesMetadata
 */



public class V1AppProfilesMetadata {
  @SerializedName("appProfiles")
  private List<V1AppProfileMetadata> appProfiles = null;

  public V1AppProfilesMetadata appProfiles(List<V1AppProfileMetadata> appProfiles) {
    this.appProfiles = appProfiles;
    return this;
  }

  public V1AppProfilesMetadata addAppProfilesItem(V1AppProfileMetadata appProfilesItem) {
    if (this.appProfiles == null) {
      this.appProfiles = new ArrayList<V1AppProfileMetadata>();
    }
    this.appProfiles.add(appProfilesItem);
    return this;
  }

   /**
   * Get appProfiles
   * @return appProfiles
  **/
  @Schema(description = "")
  public List<V1AppProfileMetadata> getAppProfiles() {
    return appProfiles;
  }

  public void setAppProfiles(List<V1AppProfileMetadata> appProfiles) {
    this.appProfiles = appProfiles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AppProfilesMetadata v1AppProfilesMetadata = (V1AppProfilesMetadata) o;
    return Objects.equals(this.appProfiles, v1AppProfilesMetadata.appProfiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appProfiles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AppProfilesMetadata {\n");
    
    sb.append("    appProfiles: ").append(toIndentedString(appProfiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
