/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1AppProfileTemplateSummary;
import com.spectrocloud.client.model.V1AppProfileVersion;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Application profile spec summary
 */
@Schema(description = "Application profile spec summary")


public class V1AppProfileSummarySpec {
  @SerializedName("parentUid")
  private String parentUid = null;

  @SerializedName("template")
  private V1AppProfileTemplateSummary template = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("versions")
  private List<V1AppProfileVersion> versions = null;

  public V1AppProfileSummarySpec parentUid(String parentUid) {
    this.parentUid = parentUid;
    return this;
  }

   /**
   * Get parentUid
   * @return parentUid
  **/
  @Schema(description = "")
  public String getParentUid() {
    return parentUid;
  }

  public void setParentUid(String parentUid) {
    this.parentUid = parentUid;
  }

  public V1AppProfileSummarySpec template(V1AppProfileTemplateSummary template) {
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @Schema(description = "")
  public V1AppProfileTemplateSummary getTemplate() {
    return template;
  }

  public void setTemplate(V1AppProfileTemplateSummary template) {
    this.template = template;
  }

  public V1AppProfileSummarySpec version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(description = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public V1AppProfileSummarySpec versions(List<V1AppProfileVersion> versions) {
    this.versions = versions;
    return this;
  }

  public V1AppProfileSummarySpec addVersionsItem(V1AppProfileVersion versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<V1AppProfileVersion>();
    }
    this.versions.add(versionsItem);
    return this;
  }

   /**
   * Application profile&#x27;s list of all the versions
   * @return versions
  **/
  @Schema(description = "Application profile's list of all the versions")
  public List<V1AppProfileVersion> getVersions() {
    return versions;
  }

  public void setVersions(List<V1AppProfileVersion> versions) {
    this.versions = versions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AppProfileSummarySpec v1AppProfileSummarySpec = (V1AppProfileSummarySpec) o;
    return Objects.equals(this.parentUid, v1AppProfileSummarySpec.parentUid) &&
        Objects.equals(this.template, v1AppProfileSummarySpec.template) &&
        Objects.equals(this.version, v1AppProfileSummarySpec.version) &&
        Objects.equals(this.versions, v1AppProfileSummarySpec.versions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parentUid, template, version, versions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AppProfileSummarySpec {\n");
    
    sb.append("    parentUid: ").append(toIndentedString(parentUid)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
