/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Audit system message
 */
@Schema(description = "Audit system message")


public class V1AuditSysMsg {
  @SerializedName("actionMsg")
  private String actionMsg = null;

  @SerializedName("contentMsg")
  private String contentMsg = null;

  public V1AuditSysMsg actionMsg(String actionMsg) {
    this.actionMsg = actionMsg;
    return this;
  }

   /**
   * Audit resource action message
   * @return actionMsg
  **/
  @Schema(description = "Audit resource action message")
  public String getActionMsg() {
    return actionMsg;
  }

  public void setActionMsg(String actionMsg) {
    this.actionMsg = actionMsg;
  }

  public V1AuditSysMsg contentMsg(String contentMsg) {
    this.contentMsg = contentMsg;
    return this;
  }

   /**
   * Audit resource content message
   * @return contentMsg
  **/
  @Schema(description = "Audit resource content message")
  public String getContentMsg() {
    return contentMsg;
  }

  public void setContentMsg(String contentMsg) {
    this.contentMsg = contentMsg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1AuditSysMsg v1AuditSysMsg = (V1AuditSysMsg) o;
    return Objects.equals(this.actionMsg, v1AuditSysMsg.actionMsg) &&
        Objects.equals(this.contentMsg, v1AuditSysMsg.contentMsg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionMsg, contentMsg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1AuditSysMsg {\n");
    
    sb.append("    actionMsg: ").append(toIndentedString(actionMsg)).append("\n");
    sb.append("    contentMsg: ").append(toIndentedString(contentMsg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
