/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1ClusterNamespace;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Cluster&#x27;s available namespaces
 */
@Schema(description = "Cluster's available namespaces")


public class V1ClusterNamespaces {
  @SerializedName("namespaces")
  private List<V1ClusterNamespace> namespaces = null;

  public V1ClusterNamespaces namespaces(List<V1ClusterNamespace> namespaces) {
    this.namespaces = namespaces;
    return this;
  }

  public V1ClusterNamespaces addNamespacesItem(V1ClusterNamespace namespacesItem) {
    if (this.namespaces == null) {
      this.namespaces = new ArrayList<V1ClusterNamespace>();
    }
    this.namespaces.add(namespacesItem);
    return this;
  }

   /**
   * Get namespaces
   * @return namespaces
  **/
  @Schema(description = "")
  public List<V1ClusterNamespace> getNamespaces() {
    return namespaces;
  }

  public void setNamespaces(List<V1ClusterNamespace> namespaces) {
    this.namespaces = namespaces;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ClusterNamespaces v1ClusterNamespaces = (V1ClusterNamespaces) o;
    return Objects.equals(this.namespaces, v1ClusterNamespaces.namespaces);
  }

  @Override
  public int hashCode() {
    return Objects.hash(namespaces);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ClusterNamespaces {\n");
    
    sb.append("    namespaces: ").append(toIndentedString(namespaces)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
