/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1ClusterWorkloadDaemonSet;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Cluster workload daemonset summary
 */
@Schema(description = "Cluster workload daemonset summary")


public class V1ClusterWorkloadDaemonSets {
  @SerializedName("daemonSets")
  private List<V1ClusterWorkloadDaemonSet> daemonSets = null;

  public V1ClusterWorkloadDaemonSets daemonSets(List<V1ClusterWorkloadDaemonSet> daemonSets) {
    this.daemonSets = daemonSets;
    return this;
  }

  public V1ClusterWorkloadDaemonSets addDaemonSetsItem(V1ClusterWorkloadDaemonSet daemonSetsItem) {
    if (this.daemonSets == null) {
      this.daemonSets = new ArrayList<V1ClusterWorkloadDaemonSet>();
    }
    this.daemonSets.add(daemonSetsItem);
    return this;
  }

   /**
   * Get daemonSets
   * @return daemonSets
  **/
  @Schema(description = "")
  public List<V1ClusterWorkloadDaemonSet> getDaemonSets() {
    return daemonSets;
  }

  public void setDaemonSets(List<V1ClusterWorkloadDaemonSet> daemonSets) {
    this.daemonSets = daemonSets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ClusterWorkloadDaemonSets v1ClusterWorkloadDaemonSets = (V1ClusterWorkloadDaemonSets) o;
    return Objects.equals(this.daemonSets, v1ClusterWorkloadDaemonSets.daemonSets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daemonSets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ClusterWorkloadDaemonSets {\n");
    
    sb.append("    daemonSets: ").append(toIndentedString(daemonSets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
