/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Cluster feature schedule
 */
@Schema(description = "Cluster feature schedule")


public class V1ClusterFeatureSchedule {
  @SerializedName("scheduledRunTime")
  private String scheduledRunTime = null;

  public V1ClusterFeatureSchedule scheduledRunTime(String scheduledRunTime) {
    this.scheduledRunTime = scheduledRunTime;
    return this;
  }

   /**
   * Get scheduledRunTime
   * @return scheduledRunTime
  **/
  @Schema(description = "")
  public String getScheduledRunTime() {
    return scheduledRunTime;
  }

  public void setScheduledRunTime(String scheduledRunTime) {
    this.scheduledRunTime = scheduledRunTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ClusterFeatureSchedule v1ClusterFeatureSchedule = (V1ClusterFeatureSchedule) o;
    return Objects.equals(this.scheduledRunTime, v1ClusterFeatureSchedule.scheduledRunTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scheduledRunTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ClusterFeatureSchedule {\n");
    
    sb.append("    scheduledRunTime: ").append(toIndentedString(scheduledRunTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
