/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Cloud instance rate config
 */
@Schema(description = "Cloud instance rate config")


public class V1CloudInstanceRateConfig {
  @SerializedName("computeRateProportion")
  private Float computeRateProportion = null;

  @SerializedName("memoryRateProportion")
  private Float memoryRateProportion = null;

  public V1CloudInstanceRateConfig computeRateProportion(Float computeRateProportion) {
    this.computeRateProportion = computeRateProportion;
    return this;
  }

   /**
   * Get computeRateProportion
   * @return computeRateProportion
  **/
  @Schema(description = "")
  public Float getComputeRateProportion() {
    return computeRateProportion;
  }

  public void setComputeRateProportion(Float computeRateProportion) {
    this.computeRateProportion = computeRateProportion;
  }

  public V1CloudInstanceRateConfig memoryRateProportion(Float memoryRateProportion) {
    this.memoryRateProportion = memoryRateProportion;
    return this;
  }

   /**
   * Get memoryRateProportion
   * @return memoryRateProportion
  **/
  @Schema(description = "")
  public Float getMemoryRateProportion() {
    return memoryRateProportion;
  }

  public void setMemoryRateProportion(Float memoryRateProportion) {
    this.memoryRateProportion = memoryRateProportion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1CloudInstanceRateConfig v1CloudInstanceRateConfig = (V1CloudInstanceRateConfig) o;
    return Objects.equals(this.computeRateProportion, v1CloudInstanceRateConfig.computeRateProportion) &&
        Objects.equals(this.memoryRateProportion, v1CloudInstanceRateConfig.memoryRateProportion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(computeRateProportion, memoryRateProportion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1CloudInstanceRateConfig {\n");
    
    sb.append("    computeRateProportion: ").append(toIndentedString(computeRateProportion)).append("\n");
    sb.append("    memoryRateProportion: ").append(toIndentedString(memoryRateProportion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
