/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1ClusterProfileStatusSummary;
import com.spectrocloud.client.model.V1ClusterProfileSummarySpecSummary;
import com.spectrocloud.client.model.V1ObjectMeta;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Cluster profile summary
 */
@Schema(description = "Cluster profile summary")


public class V1ClusterProfileSummary {
  @SerializedName("metadata")
  private V1ObjectMeta metadata = null;

  @SerializedName("specSummary")
  private V1ClusterProfileSummarySpecSummary specSummary = null;

  @SerializedName("status")
  private V1ClusterProfileStatusSummary status = null;

  public V1ClusterProfileSummary metadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @Schema(description = "")
  public V1ObjectMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
  }

  public V1ClusterProfileSummary specSummary(V1ClusterProfileSummarySpecSummary specSummary) {
    this.specSummary = specSummary;
    return this;
  }

   /**
   * Get specSummary
   * @return specSummary
  **/
  @Schema(description = "")
  public V1ClusterProfileSummarySpecSummary getSpecSummary() {
    return specSummary;
  }

  public void setSpecSummary(V1ClusterProfileSummarySpecSummary specSummary) {
    this.specSummary = specSummary;
  }

  public V1ClusterProfileSummary status(V1ClusterProfileStatusSummary status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public V1ClusterProfileStatusSummary getStatus() {
    return status;
  }

  public void setStatus(V1ClusterProfileStatusSummary status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ClusterProfileSummary v1ClusterProfileSummary = (V1ClusterProfileSummary) o;
    return Objects.equals(this.metadata, v1ClusterProfileSummary.metadata) &&
        Objects.equals(this.specSummary, v1ClusterProfileSummary.specSummary) &&
        Objects.equals(this.status, v1ClusterProfileSummary.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, specSummary, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ClusterProfileSummary {\n");
    
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    specSummary: ").append(toIndentedString(specSummary)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
