/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1ClusterWorkloadPodContainerResource;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Cluster workload pod container resources
 */
@Schema(description = "Cluster workload pod container resources")


public class V1ClusterWorkloadPodContainerResources {
  @SerializedName("limits")
  private V1ClusterWorkloadPodContainerResource limits = null;

  @SerializedName("requests")
  private V1ClusterWorkloadPodContainerResource requests = null;

  public V1ClusterWorkloadPodContainerResources limits(V1ClusterWorkloadPodContainerResource limits) {
    this.limits = limits;
    return this;
  }

   /**
   * Get limits
   * @return limits
  **/
  @Schema(description = "")
  public V1ClusterWorkloadPodContainerResource getLimits() {
    return limits;
  }

  public void setLimits(V1ClusterWorkloadPodContainerResource limits) {
    this.limits = limits;
  }

  public V1ClusterWorkloadPodContainerResources requests(V1ClusterWorkloadPodContainerResource requests) {
    this.requests = requests;
    return this;
  }

   /**
   * Get requests
   * @return requests
  **/
  @Schema(description = "")
  public V1ClusterWorkloadPodContainerResource getRequests() {
    return requests;
  }

  public void setRequests(V1ClusterWorkloadPodContainerResource requests) {
    this.requests = requests;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ClusterWorkloadPodContainerResources v1ClusterWorkloadPodContainerResources = (V1ClusterWorkloadPodContainerResources) o;
    return Objects.equals(this.limits, v1ClusterWorkloadPodContainerResources.limits) &&
        Objects.equals(this.requests, v1ClusterWorkloadPodContainerResources.requests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limits, requests);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ClusterWorkloadPodContainerResources {\n");
    
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    requests: ").append(toIndentedString(requests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
