/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1CoxEdgeMachinePoolCloudConfigEntity;
import com.spectrocloud.client.model.V1MachinePoolConfigEntity;
import com.spectrocloud.client.model.V1MachinePoolProfileConfigEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * V1CoxEdgeMachinePoolConfigEntity
 */



public class V1CoxEdgeMachinePoolConfigEntity {
  @SerializedName("cloudConfig")
  private V1CoxEdgeMachinePoolCloudConfigEntity cloudConfig = null;

  @SerializedName("poolConfig")
  private V1MachinePoolConfigEntity poolConfig = null;

  @SerializedName("profileConfig")
  private V1MachinePoolProfileConfigEntity profileConfig = null;

  public V1CoxEdgeMachinePoolConfigEntity cloudConfig(V1CoxEdgeMachinePoolCloudConfigEntity cloudConfig) {
    this.cloudConfig = cloudConfig;
    return this;
  }

   /**
   * Get cloudConfig
   * @return cloudConfig
  **/
  @Schema(required = true, description = "")
  public V1CoxEdgeMachinePoolCloudConfigEntity getCloudConfig() {
    return cloudConfig;
  }

  public void setCloudConfig(V1CoxEdgeMachinePoolCloudConfigEntity cloudConfig) {
    this.cloudConfig = cloudConfig;
  }

  public V1CoxEdgeMachinePoolConfigEntity poolConfig(V1MachinePoolConfigEntity poolConfig) {
    this.poolConfig = poolConfig;
    return this;
  }

   /**
   * Get poolConfig
   * @return poolConfig
  **/
  @Schema(description = "")
  public V1MachinePoolConfigEntity getPoolConfig() {
    return poolConfig;
  }

  public void setPoolConfig(V1MachinePoolConfigEntity poolConfig) {
    this.poolConfig = poolConfig;
  }

  public V1CoxEdgeMachinePoolConfigEntity profileConfig(V1MachinePoolProfileConfigEntity profileConfig) {
    this.profileConfig = profileConfig;
    return this;
  }

   /**
   * Get profileConfig
   * @return profileConfig
  **/
  @Schema(description = "")
  public V1MachinePoolProfileConfigEntity getProfileConfig() {
    return profileConfig;
  }

  public void setProfileConfig(V1MachinePoolProfileConfigEntity profileConfig) {
    this.profileConfig = profileConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1CoxEdgeMachinePoolConfigEntity v1CoxEdgeMachinePoolConfigEntity = (V1CoxEdgeMachinePoolConfigEntity) o;
    return Objects.equals(this.cloudConfig, v1CoxEdgeMachinePoolConfigEntity.cloudConfig) &&
        Objects.equals(this.poolConfig, v1CoxEdgeMachinePoolConfigEntity.poolConfig) &&
        Objects.equals(this.profileConfig, v1CoxEdgeMachinePoolConfigEntity.profileConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cloudConfig, poolConfig, profileConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1CoxEdgeMachinePoolConfigEntity {\n");
    
    sb.append("    cloudConfig: ").append(toIndentedString(cloudConfig)).append("\n");
    sb.append("    poolConfig: ").append(toIndentedString(poolConfig)).append("\n");
    sb.append("    profileConfig: ").append(toIndentedString(profileConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
