/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1EdgeNativeControlPlaneEndPoint;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * EdgeNativeClusterConfig definnes Edge Native Cluster specific Spec
 */
@Schema(description = "EdgeNativeClusterConfig definnes Edge Native Cluster specific Spec")


public class V1EdgeNativeClusterConfig {
  @SerializedName("controlPlaneEndpoint")
  private V1EdgeNativeControlPlaneEndPoint controlPlaneEndpoint = null;

  @SerializedName("ntpServers")
  private List<String> ntpServers = null;

  @SerializedName("sshKeys")
  private List<String> sshKeys = null;

  @SerializedName("staticIp")
  private Boolean staticIp = null;

  public V1EdgeNativeClusterConfig controlPlaneEndpoint(V1EdgeNativeControlPlaneEndPoint controlPlaneEndpoint) {
    this.controlPlaneEndpoint = controlPlaneEndpoint;
    return this;
  }

   /**
   * Get controlPlaneEndpoint
   * @return controlPlaneEndpoint
  **/
  @Schema(description = "")
  public V1EdgeNativeControlPlaneEndPoint getControlPlaneEndpoint() {
    return controlPlaneEndpoint;
  }

  public void setControlPlaneEndpoint(V1EdgeNativeControlPlaneEndPoint controlPlaneEndpoint) {
    this.controlPlaneEndpoint = controlPlaneEndpoint;
  }

  public V1EdgeNativeClusterConfig ntpServers(List<String> ntpServers) {
    this.ntpServers = ntpServers;
    return this;
  }

  public V1EdgeNativeClusterConfig addNtpServersItem(String ntpServersItem) {
    if (this.ntpServers == null) {
      this.ntpServers = new ArrayList<String>();
    }
    this.ntpServers.add(ntpServersItem);
    return this;
  }

   /**
   * NTPServers is a list of NTP servers to use instead of the machine image&#x27;s default NTP server list
   * @return ntpServers
  **/
  @Schema(description = "NTPServers is a list of NTP servers to use instead of the machine image's default NTP server list")
  public List<String> getNtpServers() {
    return ntpServers;
  }

  public void setNtpServers(List<String> ntpServers) {
    this.ntpServers = ntpServers;
  }

  public V1EdgeNativeClusterConfig sshKeys(List<String> sshKeys) {
    this.sshKeys = sshKeys;
    return this;
  }

  public V1EdgeNativeClusterConfig addSshKeysItem(String sshKeysItem) {
    if (this.sshKeys == null) {
      this.sshKeys = new ArrayList<String>();
    }
    this.sshKeys.add(sshKeysItem);
    return this;
  }

   /**
   * SSHKeys specifies a list of ssh authorized keys to access the vms as a &#x27;spectro&#x27; user
   * @return sshKeys
  **/
  @Schema(description = "SSHKeys specifies a list of ssh authorized keys to access the vms as a 'spectro' user")
  public List<String> getSshKeys() {
    return sshKeys;
  }

  public void setSshKeys(List<String> sshKeys) {
    this.sshKeys = sshKeys;
  }

  public V1EdgeNativeClusterConfig staticIp(Boolean staticIp) {
    this.staticIp = staticIp;
    return this;
  }

   /**
   * StaticIP indicates if IP allocation type is static IP. DHCP is the default allocation type
   * @return staticIp
  **/
  @Schema(description = "StaticIP indicates if IP allocation type is static IP. DHCP is the default allocation type")
  public Boolean isStaticIp() {
    return staticIp;
  }

  public void setStaticIp(Boolean staticIp) {
    this.staticIp = staticIp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1EdgeNativeClusterConfig v1EdgeNativeClusterConfig = (V1EdgeNativeClusterConfig) o;
    return Objects.equals(this.controlPlaneEndpoint, v1EdgeNativeClusterConfig.controlPlaneEndpoint) &&
        Objects.equals(this.ntpServers, v1EdgeNativeClusterConfig.ntpServers) &&
        Objects.equals(this.sshKeys, v1EdgeNativeClusterConfig.sshKeys) &&
        Objects.equals(this.staticIp, v1EdgeNativeClusterConfig.staticIp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(controlPlaneEndpoint, ntpServers, sshKeys, staticIp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1EdgeNativeClusterConfig {\n");
    
    sb.append("    controlPlaneEndpoint: ").append(toIndentedString(controlPlaneEndpoint)).append("\n");
    sb.append("    ntpServers: ").append(toIndentedString(ntpServers)).append("\n");
    sb.append("    sshKeys: ").append(toIndentedString(sshKeys)).append("\n");
    sb.append("    staticIp: ").append(toIndentedString(staticIp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
