/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * EdgeNativeHost is the underlying appliance
 */
@Schema(description = "EdgeNativeHost is the underlying appliance")


public class V1EdgeNativeHost {
  @SerializedName("IsCandidateCaption")
  private Boolean isCandidateCaption = false;

  @SerializedName("caCert")
  private String caCert = null;

  @SerializedName("hostAddress")
  private String hostAddress = "";

  @SerializedName("hostUid")
  private String hostUid = "";

  @SerializedName("nicName")
  private String nicName = null;

  @SerializedName("staticIP")
  private String staticIP = null;

  public V1EdgeNativeHost isCandidateCaption(Boolean isCandidateCaption) {
    this.isCandidateCaption = isCandidateCaption;
    return this;
  }

   /**
   * Is Edge host nominated as candidate
   * @return isCandidateCaption
  **/
  @Schema(description = "Is Edge host nominated as candidate")
  public Boolean isIsCandidateCaption() {
    return isCandidateCaption;
  }

  public void setIsCandidateCaption(Boolean isCandidateCaption) {
    this.isCandidateCaption = isCandidateCaption;
  }

  public V1EdgeNativeHost caCert(String caCert) {
    this.caCert = caCert;
    return this;
  }

   /**
   * CACert for TLS connections
   * @return caCert
  **/
  @Schema(description = "CACert for TLS connections")
  public String getCaCert() {
    return caCert;
  }

  public void setCaCert(String caCert) {
    this.caCert = caCert;
  }

  public V1EdgeNativeHost hostAddress(String hostAddress) {
    this.hostAddress = hostAddress;
    return this;
  }

   /**
   * HostAddress is a FQDN or IP address of the Host
   * @return hostAddress
  **/
  @Schema(required = true, description = "HostAddress is a FQDN or IP address of the Host")
  public String getHostAddress() {
    return hostAddress;
  }

  public void setHostAddress(String hostAddress) {
    this.hostAddress = hostAddress;
  }

  public V1EdgeNativeHost hostUid(String hostUid) {
    this.hostUid = hostUid;
    return this;
  }

   /**
   * HostUid is the ID of the EdgeHost
   * @return hostUid
  **/
  @Schema(required = true, description = "HostUid is the ID of the EdgeHost")
  public String getHostUid() {
    return hostUid;
  }

  public void setHostUid(String hostUid) {
    this.hostUid = hostUid;
  }

  public V1EdgeNativeHost nicName(String nicName) {
    this.nicName = nicName;
    return this;
  }

   /**
   * Edge host nic name
   * @return nicName
  **/
  @Schema(description = "Edge host nic name")
  public String getNicName() {
    return nicName;
  }

  public void setNicName(String nicName) {
    this.nicName = nicName;
  }

  public V1EdgeNativeHost staticIP(String staticIP) {
    this.staticIP = staticIP;
    return this;
  }

   /**
   * Edge host static IP
   * @return staticIP
  **/
  @Schema(description = "Edge host static IP")
  public String getStaticIP() {
    return staticIP;
  }

  public void setStaticIP(String staticIP) {
    this.staticIP = staticIP;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1EdgeNativeHost v1EdgeNativeHost = (V1EdgeNativeHost) o;
    return Objects.equals(this.isCandidateCaption, v1EdgeNativeHost.isCandidateCaption) &&
        Objects.equals(this.caCert, v1EdgeNativeHost.caCert) &&
        Objects.equals(this.hostAddress, v1EdgeNativeHost.hostAddress) &&
        Objects.equals(this.hostUid, v1EdgeNativeHost.hostUid) &&
        Objects.equals(this.nicName, v1EdgeNativeHost.nicName) &&
        Objects.equals(this.staticIP, v1EdgeNativeHost.staticIP);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isCandidateCaption, caCert, hostAddress, hostUid, nicName, staticIP);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1EdgeNativeHost {\n");
    
    sb.append("    isCandidateCaption: ").append(toIndentedString(isCandidateCaption)).append("\n");
    sb.append("    caCert: ").append(toIndentedString(caCert)).append("\n");
    sb.append("    hostAddress: ").append(toIndentedString(hostAddress)).append("\n");
    sb.append("    hostUid: ").append(toIndentedString(hostUid)).append("\n");
    sb.append("    nicName: ").append(toIndentedString(nicName)).append("\n");
    sb.append("    staticIP: ").append(toIndentedString(staticIP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
