/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1GcpNetwork;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * List of GCP networks
 */
@Schema(description = "List of GCP networks")


public class V1GcpNetworks {
  @SerializedName("networks")
  private List<V1GcpNetwork> networks = null;

  public V1GcpNetworks networks(List<V1GcpNetwork> networks) {
    this.networks = networks;
    return this;
  }

  public V1GcpNetworks addNetworksItem(V1GcpNetwork networksItem) {
    if (this.networks == null) {
      this.networks = new ArrayList<V1GcpNetwork>();
    }
    this.networks.add(networksItem);
    return this;
  }

   /**
   * Get networks
   * @return networks
  **/
  @Schema(description = "")
  public List<V1GcpNetwork> getNetworks() {
    return networks;
  }

  public void setNetworks(List<V1GcpNetwork> networks) {
    this.networks = networks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GcpNetworks v1GcpNetworks = (V1GcpNetworks) o;
    return Objects.equals(this.networks, v1GcpNetworks.networks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GcpNetworks {\n");
    
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
