/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Invoice credits object
 */
@Schema(description = "Invoice credits object")


public class V1InvoiceCredits {
  @SerializedName("alloyFreeCredits")
  private BigDecimal alloyFreeCredits = null;

  @SerializedName("pureFreeCredits")
  private BigDecimal pureFreeCredits = null;

  public V1InvoiceCredits alloyFreeCredits(BigDecimal alloyFreeCredits) {
    this.alloyFreeCredits = alloyFreeCredits;
    return this;
  }

   /**
   * Credits allocated for import clusters
   * @return alloyFreeCredits
  **/
  @Schema(description = "Credits allocated for import clusters")
  public BigDecimal getAlloyFreeCredits() {
    return alloyFreeCredits;
  }

  public void setAlloyFreeCredits(BigDecimal alloyFreeCredits) {
    this.alloyFreeCredits = alloyFreeCredits;
  }

  public V1InvoiceCredits pureFreeCredits(BigDecimal pureFreeCredits) {
    this.pureFreeCredits = pureFreeCredits;
    return this;
  }

   /**
   * Credits allocated for managed clusters
   * @return pureFreeCredits
  **/
  @Schema(description = "Credits allocated for managed clusters")
  public BigDecimal getPureFreeCredits() {
    return pureFreeCredits;
  }

  public void setPureFreeCredits(BigDecimal pureFreeCredits) {
    this.pureFreeCredits = pureFreeCredits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1InvoiceCredits v1InvoiceCredits = (V1InvoiceCredits) o;
    return Objects.equals(this.alloyFreeCredits, v1InvoiceCredits.alloyFreeCredits) &&
        Objects.equals(this.pureFreeCredits, v1InvoiceCredits.pureFreeCredits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alloyFreeCredits, pureFreeCredits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1InvoiceCredits {\n");
    
    sb.append("    alloyFreeCredits: ").append(toIndentedString(alloyFreeCredits)).append("\n");
    sb.append("    pureFreeCredits: ").append(toIndentedString(pureFreeCredits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
