/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1InvoiceProduct;
import com.spectrocloud.client.model.V1InvoiceProject;
import com.spectrocloud.client.model.V1InvoiceState;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * Invoice Status
 */
@Schema(description = "Invoice Status")


public class V1InvoiceStatus {
  @SerializedName("billableAmount")
  private BigDecimal billableAmount = null;

  @SerializedName("productInvoice")
  private V1InvoiceProduct productInvoice = null;

  @SerializedName("projects")
  private List<V1InvoiceProject> projects = null;

  @SerializedName("states")
  private List<V1InvoiceState> states = null;

  @SerializedName("stripeInvoiceId")
  private String stripeInvoiceId = null;

  public V1InvoiceStatus billableAmount(BigDecimal billableAmount) {
    this.billableAmount = billableAmount;
    return this;
  }

   /**
   * Total billable amount
   * @return billableAmount
  **/
  @Schema(description = "Total billable amount")
  public BigDecimal getBillableAmount() {
    return billableAmount;
  }

  public void setBillableAmount(BigDecimal billableAmount) {
    this.billableAmount = billableAmount;
  }

  public V1InvoiceStatus productInvoice(V1InvoiceProduct productInvoice) {
    this.productInvoice = productInvoice;
    return this;
  }

   /**
   * Get productInvoice
   * @return productInvoice
  **/
  @Schema(description = "")
  public V1InvoiceProduct getProductInvoice() {
    return productInvoice;
  }

  public void setProductInvoice(V1InvoiceProduct productInvoice) {
    this.productInvoice = productInvoice;
  }

  public V1InvoiceStatus projects(List<V1InvoiceProject> projects) {
    this.projects = projects;
    return this;
  }

  public V1InvoiceStatus addProjectsItem(V1InvoiceProject projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<V1InvoiceProject>();
    }
    this.projects.add(projectsItem);
    return this;
  }

   /**
   * List of project invoices
   * @return projects
  **/
  @Schema(description = "List of project invoices")
  public List<V1InvoiceProject> getProjects() {
    return projects;
  }

  public void setProjects(List<V1InvoiceProject> projects) {
    this.projects = projects;
  }

  public V1InvoiceStatus states(List<V1InvoiceState> states) {
    this.states = states;
    return this;
  }

  public V1InvoiceStatus addStatesItem(V1InvoiceState statesItem) {
    if (this.states == null) {
      this.states = new ArrayList<V1InvoiceState>();
    }
    this.states.add(statesItem);
    return this;
  }

   /**
   * List of invoice states
   * @return states
  **/
  @Schema(description = "List of invoice states")
  public List<V1InvoiceState> getStates() {
    return states;
  }

  public void setStates(List<V1InvoiceState> states) {
    this.states = states;
  }

  public V1InvoiceStatus stripeInvoiceId(String stripeInvoiceId) {
    this.stripeInvoiceId = stripeInvoiceId;
    return this;
  }

   /**
   * Stripe invoice uid
   * @return stripeInvoiceId
  **/
  @Schema(description = "Stripe invoice uid")
  public String getStripeInvoiceId() {
    return stripeInvoiceId;
  }

  public void setStripeInvoiceId(String stripeInvoiceId) {
    this.stripeInvoiceId = stripeInvoiceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1InvoiceStatus v1InvoiceStatus = (V1InvoiceStatus) o;
    return Objects.equals(this.billableAmount, v1InvoiceStatus.billableAmount) &&
        Objects.equals(this.productInvoice, v1InvoiceStatus.productInvoice) &&
        Objects.equals(this.projects, v1InvoiceStatus.projects) &&
        Objects.equals(this.states, v1InvoiceStatus.states) &&
        Objects.equals(this.stripeInvoiceId, v1InvoiceStatus.stripeInvoiceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billableAmount, productInvoice, projects, states, stripeInvoiceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1InvoiceStatus {\n");
    
    sb.append("    billableAmount: ").append(toIndentedString(billableAmount)).append("\n");
    sb.append("    productInvoice: ").append(toIndentedString(productInvoice)).append("\n");
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    states: ").append(toIndentedString(states)).append("\n");
    sb.append("    stripeInvoiceId: ").append(toIndentedString(stripeInvoiceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
