/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * V1InstanceConfig
 */



public class V1InstanceConfig {
  @SerializedName("category")
  private String category = null;

  @SerializedName("cpuSet")
  private Long cpuSet = null;

  @SerializedName("diskGiB")
  private Long diskGiB = null;

  @SerializedName("memoryMiB")
  private Long memoryMiB = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("numCPUs")
  private Integer numCPUs = null;

  public V1InstanceConfig category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @Schema(description = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public V1InstanceConfig cpuSet(Long cpuSet) {
    this.cpuSet = cpuSet;
    return this;
  }

   /**
   * Get cpuSet
   * @return cpuSet
  **/
  @Schema(description = "")
  public Long getCpuSet() {
    return cpuSet;
  }

  public void setCpuSet(Long cpuSet) {
    this.cpuSet = cpuSet;
  }

  public V1InstanceConfig diskGiB(Long diskGiB) {
    this.diskGiB = diskGiB;
    return this;
  }

   /**
   * Get diskGiB
   * @return diskGiB
  **/
  @Schema(description = "")
  public Long getDiskGiB() {
    return diskGiB;
  }

  public void setDiskGiB(Long diskGiB) {
    this.diskGiB = diskGiB;
  }

  public V1InstanceConfig memoryMiB(Long memoryMiB) {
    this.memoryMiB = memoryMiB;
    return this;
  }

   /**
   * MemoryMiB is the size of a virtual machine&#x27;s memory, in MiB
   * @return memoryMiB
  **/
  @Schema(description = "MemoryMiB is the size of a virtual machine's memory, in MiB")
  public Long getMemoryMiB() {
    return memoryMiB;
  }

  public void setMemoryMiB(Long memoryMiB) {
    this.memoryMiB = memoryMiB;
  }

  public V1InstanceConfig name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public V1InstanceConfig numCPUs(Integer numCPUs) {
    this.numCPUs = numCPUs;
    return this;
  }

   /**
   * NumCPUs is the number of virtual processors in a virtual machine
   * @return numCPUs
  **/
  @Schema(description = "NumCPUs is the number of virtual processors in a virtual machine")
  public Integer getNumCPUs() {
    return numCPUs;
  }

  public void setNumCPUs(Integer numCPUs) {
    this.numCPUs = numCPUs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1InstanceConfig v1InstanceConfig = (V1InstanceConfig) o;
    return Objects.equals(this.category, v1InstanceConfig.category) &&
        Objects.equals(this.cpuSet, v1InstanceConfig.cpuSet) &&
        Objects.equals(this.diskGiB, v1InstanceConfig.diskGiB) &&
        Objects.equals(this.memoryMiB, v1InstanceConfig.memoryMiB) &&
        Objects.equals(this.name, v1InstanceConfig.name) &&
        Objects.equals(this.numCPUs, v1InstanceConfig.numCPUs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, cpuSet, diskGiB, memoryMiB, name, numCPUs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1InstanceConfig {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    cpuSet: ").append(toIndentedString(cpuSet)).append("\n");
    sb.append("    diskGiB: ").append(toIndentedString(diskGiB)).append("\n");
    sb.append("    memoryMiB: ").append(toIndentedString(memoryMiB)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    numCPUs: ").append(toIndentedString(numCPUs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
