/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1PackValuesEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1MachinePoolProfileConfigEntity
 */



public class V1MachinePoolProfileConfigEntity {
  @SerializedName("infraProfileUid")
  private String infraProfileUid = null;

  @SerializedName("packValues")
  private List<V1PackValuesEntity> packValues = null;

  public V1MachinePoolProfileConfigEntity infraProfileUid(String infraProfileUid) {
    this.infraProfileUid = infraProfileUid;
    return this;
  }

   /**
   * InfraClusterProfile uid for the machine pool
   * @return infraProfileUid
  **/
  @Schema(required = true, description = "InfraClusterProfile uid for the machine pool")
  public String getInfraProfileUid() {
    return infraProfileUid;
  }

  public void setInfraProfileUid(String infraProfileUid) {
    this.infraProfileUid = infraProfileUid;
  }

  public V1MachinePoolProfileConfigEntity packValues(List<V1PackValuesEntity> packValues) {
    this.packValues = packValues;
    return this;
  }

  public V1MachinePoolProfileConfigEntity addPackValuesItem(V1PackValuesEntity packValuesItem) {
    if (this.packValues == null) {
      this.packValues = new ArrayList<V1PackValuesEntity>();
    }
    this.packValues.add(packValuesItem);
    return this;
  }

   /**
   * Get packValues
   * @return packValues
  **/
  @Schema(description = "")
  public List<V1PackValuesEntity> getPackValues() {
    return packValues;
  }

  public void setPackValues(List<V1PackValuesEntity> packValues) {
    this.packValues = packValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1MachinePoolProfileConfigEntity v1MachinePoolProfileConfigEntity = (V1MachinePoolProfileConfigEntity) o;
    return Objects.equals(this.infraProfileUid, v1MachinePoolProfileConfigEntity.infraProfileUid) &&
        Objects.equals(this.packValues, v1MachinePoolProfileConfigEntity.packValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(infraProfileUid, packValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1MachinePoolProfileConfigEntity {\n");
    
    sb.append("    infraProfileUid: ").append(toIndentedString(infraProfileUid)).append("\n");
    sb.append("    packValues: ").append(toIndentedString(packValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
