/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1MachineUids
 */



public class V1MachineUids {
  @SerializedName("machineUids")
  private List<String> machineUids = null;

  public V1MachineUids machineUids(List<String> machineUids) {
    this.machineUids = machineUids;
    return this;
  }

  public V1MachineUids addMachineUidsItem(String machineUidsItem) {
    if (this.machineUids == null) {
      this.machineUids = new ArrayList<String>();
    }
    this.machineUids.add(machineUidsItem);
    return this;
  }

   /**
   * Get machineUids
   * @return machineUids
  **/
  @Schema(description = "")
  public List<String> getMachineUids() {
    return machineUids;
  }

  public void setMachineUids(List<String> machineUids) {
    this.machineUids = machineUids;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1MachineUids v1MachineUids = (V1MachineUids) o;
    return Objects.equals(this.machineUids, v1MachineUids.machineUids);
  }

  @Override
  public int hashCode() {
    return Objects.hash(machineUids);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1MachineUids {\n");
    
    sb.append("    machineUids: ").append(toIndentedString(machineUids)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
