/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Maas vlan entity
 */
@Schema(description = "Maas vlan entity")


public class V1MaasVlan {
  @SerializedName("fabric")
  private String fabric = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  public V1MaasVlan fabric(String fabric) {
    this.fabric = fabric;
    return this;
  }

   /**
   * Fabric associated with Maas Vlan
   * @return fabric
  **/
  @Schema(description = "Fabric associated with Maas Vlan")
  public String getFabric() {
    return fabric;
  }

  public void setFabric(String fabric) {
    this.fabric = fabric;
  }

  public V1MaasVlan id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Id of Maas Vlan
   * @return id
  **/
  @Schema(description = "Id of Maas Vlan")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public V1MaasVlan name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of Maas Vlan
   * @return name
  **/
  @Schema(description = "Name of Maas Vlan")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1MaasVlan v1MaasVlan = (V1MaasVlan) o;
    return Objects.equals(this.fabric, v1MaasVlan.fabric) &&
        Objects.equals(this.id, v1MaasVlan.id) &&
        Objects.equals(this.name, v1MaasVlan.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fabric, id, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1MaasVlan {\n");
    
    sb.append("    fabric: ").append(toIndentedString(fabric)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
