/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1Macro;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1Macros
 */



public class V1Macros {
  @SerializedName("macros")
  private List<V1Macro> macros = null;

  public V1Macros macros(List<V1Macro> macros) {
    this.macros = macros;
    return this;
  }

  public V1Macros addMacrosItem(V1Macro macrosItem) {
    if (this.macros == null) {
      this.macros = new ArrayList<V1Macro>();
    }
    this.macros.add(macrosItem);
    return this;
  }

   /**
   * Get macros
   * @return macros
  **/
  @Schema(description = "")
  public List<V1Macro> getMacros() {
    return macros;
  }

  public void setMacros(List<V1Macro> macros) {
    this.macros = macros;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1Macros v1Macros = (V1Macros) o;
    return Objects.equals(this.macros, v1Macros.macros);
  }

  @Override
  public int hashCode() {
    return Objects.hash(macros);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1Macros {\n");
    
    sb.append("    macros: ").append(toIndentedString(macros)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
