/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1MaasCloudAccount
 */



public class V1MaasCloudAccount {
  @SerializedName("apiEndpoint")
  private String apiEndpoint = null;

  @SerializedName("apiKey")
  private String apiKey = null;

  @SerializedName("preferredSubnets")
  private List<String> preferredSubnets = null;

  public V1MaasCloudAccount apiEndpoint(String apiEndpoint) {
    this.apiEndpoint = apiEndpoint;
    return this;
  }

   /**
   * Get apiEndpoint
   * @return apiEndpoint
  **/
  @Schema(required = true, description = "")
  public String getApiEndpoint() {
    return apiEndpoint;
  }

  public void setApiEndpoint(String apiEndpoint) {
    this.apiEndpoint = apiEndpoint;
  }

  public V1MaasCloudAccount apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Get apiKey
   * @return apiKey
  **/
  @Schema(required = true, description = "")
  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  public V1MaasCloudAccount preferredSubnets(List<String> preferredSubnets) {
    this.preferredSubnets = preferredSubnets;
    return this;
  }

  public V1MaasCloudAccount addPreferredSubnetsItem(String preferredSubnetsItem) {
    if (this.preferredSubnets == null) {
      this.preferredSubnets = new ArrayList<String>();
    }
    this.preferredSubnets.add(preferredSubnetsItem);
    return this;
  }

   /**
   * list of preferred subnets order in the list reflects order in which subnets will be selected for ip address selection in apiserver dns endpoint this way user can specify external or preferable subnet \&quot;10.11.130.0/24,10.10.10.0/24\&quot;
   * @return preferredSubnets
  **/
  @Schema(description = "list of preferred subnets order in the list reflects order in which subnets will be selected for ip address selection in apiserver dns endpoint this way user can specify external or preferable subnet \"10.11.130.0/24,10.10.10.0/24\"")
  public List<String> getPreferredSubnets() {
    return preferredSubnets;
  }

  public void setPreferredSubnets(List<String> preferredSubnets) {
    this.preferredSubnets = preferredSubnets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1MaasCloudAccount v1MaasCloudAccount = (V1MaasCloudAccount) o;
    return Objects.equals(this.apiEndpoint, v1MaasCloudAccount.apiEndpoint) &&
        Objects.equals(this.apiKey, v1MaasCloudAccount.apiKey) &&
        Objects.equals(this.preferredSubnets, v1MaasCloudAccount.preferredSubnets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiEndpoint, apiKey, preferredSubnets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1MaasCloudAccount {\n");
    
    sb.append("    apiEndpoint: ").append(toIndentedString(apiEndpoint)).append("\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    preferredSubnets: ").append(toIndentedString(preferredSubnets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
