/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1RegistryAuth;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Oci registry credentials
 */
@Schema(description = "Oci registry credentials")


public class V1OciRegistryEntity {
  @SerializedName("auth")
  private V1RegistryAuth auth = null;

  @SerializedName("defaultRegion")
  private String defaultRegion = null;

  @SerializedName("endpoint")
  private String endpoint = null;

  @SerializedName("providerType")
  private String providerType = null;

  @SerializedName("scope")
  private String scope = null;

  @SerializedName("type")
  private String type = null;

  public V1OciRegistryEntity auth(V1RegistryAuth auth) {
    this.auth = auth;
    return this;
  }

   /**
   * Get auth
   * @return auth
  **/
  @Schema(description = "")
  public V1RegistryAuth getAuth() {
    return auth;
  }

  public void setAuth(V1RegistryAuth auth) {
    this.auth = auth;
  }

  public V1OciRegistryEntity defaultRegion(String defaultRegion) {
    this.defaultRegion = defaultRegion;
    return this;
  }

   /**
   * Get defaultRegion
   * @return defaultRegion
  **/
  @Schema(description = "")
  public String getDefaultRegion() {
    return defaultRegion;
  }

  public void setDefaultRegion(String defaultRegion) {
    this.defaultRegion = defaultRegion;
  }

  public V1OciRegistryEntity endpoint(String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Get endpoint
   * @return endpoint
  **/
  @Schema(description = "")
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  public V1OciRegistryEntity providerType(String providerType) {
    this.providerType = providerType;
    return this;
  }

   /**
   * Get providerType
   * @return providerType
  **/
  @Schema(description = "")
  public String getProviderType() {
    return providerType;
  }

  public void setProviderType(String providerType) {
    this.providerType = providerType;
  }

  public V1OciRegistryEntity scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @Schema(description = "")
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }

  public V1OciRegistryEntity type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1OciRegistryEntity v1OciRegistryEntity = (V1OciRegistryEntity) o;
    return Objects.equals(this.auth, v1OciRegistryEntity.auth) &&
        Objects.equals(this.defaultRegion, v1OciRegistryEntity.defaultRegion) &&
        Objects.equals(this.endpoint, v1OciRegistryEntity.endpoint) &&
        Objects.equals(this.providerType, v1OciRegistryEntity.providerType) &&
        Objects.equals(this.scope, v1OciRegistryEntity.scope) &&
        Objects.equals(this.type, v1OciRegistryEntity.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auth, defaultRegion, endpoint, providerType, scope, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1OciRegistryEntity {\n");
    
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("    defaultRegion: ").append(toIndentedString(defaultRegion)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    providerType: ").append(toIndentedString(providerType)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
