/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1PrivateCloudRateConfig;
import com.spectrocloud.client.model.V1PublicCloudRateConfig;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Rate config
 */
@Schema(description = "Rate config")


public class V1RateConfig {
  @SerializedName("aws")
  private V1PublicCloudRateConfig aws = null;

  @SerializedName("azure")
  private V1PublicCloudRateConfig azure = null;

  @SerializedName("coxedge")
  private V1PublicCloudRateConfig coxedge = null;

  @SerializedName("edge")
  private V1PrivateCloudRateConfig edge = null;

  @SerializedName("edgeNative")
  private V1PrivateCloudRateConfig edgeNative = null;

  @SerializedName("gcp")
  private V1PublicCloudRateConfig gcp = null;

  @SerializedName("generic")
  private V1PrivateCloudRateConfig generic = null;

  @SerializedName("libvirt")
  private V1PrivateCloudRateConfig libvirt = null;

  @SerializedName("maas")
  private V1PrivateCloudRateConfig maas = null;

  @SerializedName("openstack")
  private V1PrivateCloudRateConfig openstack = null;

  @SerializedName("vsphere")
  private V1PrivateCloudRateConfig vsphere = null;

  public V1RateConfig aws(V1PublicCloudRateConfig aws) {
    this.aws = aws;
    return this;
  }

   /**
   * Get aws
   * @return aws
  **/
  @Schema(description = "")
  public V1PublicCloudRateConfig getAws() {
    return aws;
  }

  public void setAws(V1PublicCloudRateConfig aws) {
    this.aws = aws;
  }

  public V1RateConfig azure(V1PublicCloudRateConfig azure) {
    this.azure = azure;
    return this;
  }

   /**
   * Get azure
   * @return azure
  **/
  @Schema(description = "")
  public V1PublicCloudRateConfig getAzure() {
    return azure;
  }

  public void setAzure(V1PublicCloudRateConfig azure) {
    this.azure = azure;
  }

  public V1RateConfig coxedge(V1PublicCloudRateConfig coxedge) {
    this.coxedge = coxedge;
    return this;
  }

   /**
   * Get coxedge
   * @return coxedge
  **/
  @Schema(description = "")
  public V1PublicCloudRateConfig getCoxedge() {
    return coxedge;
  }

  public void setCoxedge(V1PublicCloudRateConfig coxedge) {
    this.coxedge = coxedge;
  }

  public V1RateConfig edge(V1PrivateCloudRateConfig edge) {
    this.edge = edge;
    return this;
  }

   /**
   * Get edge
   * @return edge
  **/
  @Schema(description = "")
  public V1PrivateCloudRateConfig getEdge() {
    return edge;
  }

  public void setEdge(V1PrivateCloudRateConfig edge) {
    this.edge = edge;
  }

  public V1RateConfig edgeNative(V1PrivateCloudRateConfig edgeNative) {
    this.edgeNative = edgeNative;
    return this;
  }

   /**
   * Get edgeNative
   * @return edgeNative
  **/
  @Schema(description = "")
  public V1PrivateCloudRateConfig getEdgeNative() {
    return edgeNative;
  }

  public void setEdgeNative(V1PrivateCloudRateConfig edgeNative) {
    this.edgeNative = edgeNative;
  }

  public V1RateConfig gcp(V1PublicCloudRateConfig gcp) {
    this.gcp = gcp;
    return this;
  }

   /**
   * Get gcp
   * @return gcp
  **/
  @Schema(description = "")
  public V1PublicCloudRateConfig getGcp() {
    return gcp;
  }

  public void setGcp(V1PublicCloudRateConfig gcp) {
    this.gcp = gcp;
  }

  public V1RateConfig generic(V1PrivateCloudRateConfig generic) {
    this.generic = generic;
    return this;
  }

   /**
   * Get generic
   * @return generic
  **/
  @Schema(description = "")
  public V1PrivateCloudRateConfig getGeneric() {
    return generic;
  }

  public void setGeneric(V1PrivateCloudRateConfig generic) {
    this.generic = generic;
  }

  public V1RateConfig libvirt(V1PrivateCloudRateConfig libvirt) {
    this.libvirt = libvirt;
    return this;
  }

   /**
   * Get libvirt
   * @return libvirt
  **/
  @Schema(description = "")
  public V1PrivateCloudRateConfig getLibvirt() {
    return libvirt;
  }

  public void setLibvirt(V1PrivateCloudRateConfig libvirt) {
    this.libvirt = libvirt;
  }

  public V1RateConfig maas(V1PrivateCloudRateConfig maas) {
    this.maas = maas;
    return this;
  }

   /**
   * Get maas
   * @return maas
  **/
  @Schema(description = "")
  public V1PrivateCloudRateConfig getMaas() {
    return maas;
  }

  public void setMaas(V1PrivateCloudRateConfig maas) {
    this.maas = maas;
  }

  public V1RateConfig openstack(V1PrivateCloudRateConfig openstack) {
    this.openstack = openstack;
    return this;
  }

   /**
   * Get openstack
   * @return openstack
  **/
  @Schema(description = "")
  public V1PrivateCloudRateConfig getOpenstack() {
    return openstack;
  }

  public void setOpenstack(V1PrivateCloudRateConfig openstack) {
    this.openstack = openstack;
  }

  public V1RateConfig vsphere(V1PrivateCloudRateConfig vsphere) {
    this.vsphere = vsphere;
    return this;
  }

   /**
   * Get vsphere
   * @return vsphere
  **/
  @Schema(description = "")
  public V1PrivateCloudRateConfig getVsphere() {
    return vsphere;
  }

  public void setVsphere(V1PrivateCloudRateConfig vsphere) {
    this.vsphere = vsphere;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1RateConfig v1RateConfig = (V1RateConfig) o;
    return Objects.equals(this.aws, v1RateConfig.aws) &&
        Objects.equals(this.azure, v1RateConfig.azure) &&
        Objects.equals(this.coxedge, v1RateConfig.coxedge) &&
        Objects.equals(this.edge, v1RateConfig.edge) &&
        Objects.equals(this.edgeNative, v1RateConfig.edgeNative) &&
        Objects.equals(this.gcp, v1RateConfig.gcp) &&
        Objects.equals(this.generic, v1RateConfig.generic) &&
        Objects.equals(this.libvirt, v1RateConfig.libvirt) &&
        Objects.equals(this.maas, v1RateConfig.maas) &&
        Objects.equals(this.openstack, v1RateConfig.openstack) &&
        Objects.equals(this.vsphere, v1RateConfig.vsphere);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aws, azure, coxedge, edge, edgeNative, gcp, generic, libvirt, maas, openstack, vsphere);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1RateConfig {\n");
    
    sb.append("    aws: ").append(toIndentedString(aws)).append("\n");
    sb.append("    azure: ").append(toIndentedString(azure)).append("\n");
    sb.append("    coxedge: ").append(toIndentedString(coxedge)).append("\n");
    sb.append("    edge: ").append(toIndentedString(edge)).append("\n");
    sb.append("    edgeNative: ").append(toIndentedString(edgeNative)).append("\n");
    sb.append("    gcp: ").append(toIndentedString(gcp)).append("\n");
    sb.append("    generic: ").append(toIndentedString(generic)).append("\n");
    sb.append("    libvirt: ").append(toIndentedString(libvirt)).append("\n");
    sb.append("    maas: ").append(toIndentedString(maas)).append("\n");
    sb.append("    openstack: ").append(toIndentedString(openstack)).append("\n");
    sb.append("    vsphere: ").append(toIndentedString(vsphere)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
