/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1ProjectResourceUsage;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * ResourceUsage
 */
@Schema(description = "ResourceUsage")


public class V1ResourceUsage {
  @SerializedName("projects")
  private List<V1ProjectResourceUsage> projects = null;

  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  @SerializedName("totalAlloyCpuCoreHours")
  private BigDecimal totalAlloyCpuCoreHours = null;

  @SerializedName("totalPureCpuCoreHours")
  private BigDecimal totalPureCpuCoreHours = null;

  public V1ResourceUsage projects(List<V1ProjectResourceUsage> projects) {
    this.projects = projects;
    return this;
  }

  public V1ResourceUsage addProjectsItem(V1ProjectResourceUsage projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<V1ProjectResourceUsage>();
    }
    this.projects.add(projectsItem);
    return this;
  }

   /**
   * Get projects
   * @return projects
  **/
  @Schema(description = "")
  public List<V1ProjectResourceUsage> getProjects() {
    return projects;
  }

  public void setProjects(List<V1ProjectResourceUsage> projects) {
    this.projects = projects;
  }

  public V1ResourceUsage timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(description = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public V1ResourceUsage totalAlloyCpuCoreHours(BigDecimal totalAlloyCpuCoreHours) {
    this.totalAlloyCpuCoreHours = totalAlloyCpuCoreHours;
    return this;
  }

   /**
   * Get totalAlloyCpuCoreHours
   * @return totalAlloyCpuCoreHours
  **/
  @Schema(description = "")
  public BigDecimal getTotalAlloyCpuCoreHours() {
    return totalAlloyCpuCoreHours;
  }

  public void setTotalAlloyCpuCoreHours(BigDecimal totalAlloyCpuCoreHours) {
    this.totalAlloyCpuCoreHours = totalAlloyCpuCoreHours;
  }

  public V1ResourceUsage totalPureCpuCoreHours(BigDecimal totalPureCpuCoreHours) {
    this.totalPureCpuCoreHours = totalPureCpuCoreHours;
    return this;
  }

   /**
   * Get totalPureCpuCoreHours
   * @return totalPureCpuCoreHours
  **/
  @Schema(description = "")
  public BigDecimal getTotalPureCpuCoreHours() {
    return totalPureCpuCoreHours;
  }

  public void setTotalPureCpuCoreHours(BigDecimal totalPureCpuCoreHours) {
    this.totalPureCpuCoreHours = totalPureCpuCoreHours;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ResourceUsage v1ResourceUsage = (V1ResourceUsage) o;
    return Objects.equals(this.projects, v1ResourceUsage.projects) &&
        Objects.equals(this.timestamp, v1ResourceUsage.timestamp) &&
        Objects.equals(this.totalAlloyCpuCoreHours, v1ResourceUsage.totalAlloyCpuCoreHours) &&
        Objects.equals(this.totalPureCpuCoreHours, v1ResourceUsage.totalPureCpuCoreHours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projects, timestamp, totalAlloyCpuCoreHours, totalPureCpuCoreHours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ResourceUsage {\n");
    
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    totalAlloyCpuCoreHours: ").append(toIndentedString(totalAlloyCpuCoreHours)).append("\n");
    sb.append("    totalPureCpuCoreHours: ").append(toIndentedString(totalPureCpuCoreHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
