/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1ResourceRolesUpdateEntity
 */



public class V1ResourceRolesUpdateEntity {
  @SerializedName("filterRefs")
  private List<String> filterRefs = null;

  @SerializedName("projectUids")
  private List<String> projectUids = null;

  @SerializedName("roles")
  private List<String> roles = null;

  public V1ResourceRolesUpdateEntity filterRefs(List<String> filterRefs) {
    this.filterRefs = filterRefs;
    return this;
  }

  public V1ResourceRolesUpdateEntity addFilterRefsItem(String filterRefsItem) {
    if (this.filterRefs == null) {
      this.filterRefs = new ArrayList<String>();
    }
    this.filterRefs.add(filterRefsItem);
    return this;
  }

   /**
   * Get filterRefs
   * @return filterRefs
  **/
  @Schema(description = "")
  public List<String> getFilterRefs() {
    return filterRefs;
  }

  public void setFilterRefs(List<String> filterRefs) {
    this.filterRefs = filterRefs;
  }

  public V1ResourceRolesUpdateEntity projectUids(List<String> projectUids) {
    this.projectUids = projectUids;
    return this;
  }

  public V1ResourceRolesUpdateEntity addProjectUidsItem(String projectUidsItem) {
    if (this.projectUids == null) {
      this.projectUids = new ArrayList<String>();
    }
    this.projectUids.add(projectUidsItem);
    return this;
  }

   /**
   * Get projectUids
   * @return projectUids
  **/
  @Schema(description = "")
  public List<String> getProjectUids() {
    return projectUids;
  }

  public void setProjectUids(List<String> projectUids) {
    this.projectUids = projectUids;
  }

  public V1ResourceRolesUpdateEntity roles(List<String> roles) {
    this.roles = roles;
    return this;
  }

  public V1ResourceRolesUpdateEntity addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<String>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @Schema(description = "")
  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(List<String> roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ResourceRolesUpdateEntity v1ResourceRolesUpdateEntity = (V1ResourceRolesUpdateEntity) o;
    return Objects.equals(this.filterRefs, v1ResourceRolesUpdateEntity.filterRefs) &&
        Objects.equals(this.projectUids, v1ResourceRolesUpdateEntity.projectUids) &&
        Objects.equals(this.roles, v1ResourceRolesUpdateEntity.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filterRefs, projectUids, roles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ResourceRolesUpdateEntity {\n");
    
    sb.append("    filterRefs: ").append(toIndentedString(filterRefs)).append("\n");
    sb.append("    projectUids: ").append(toIndentedString(projectUids)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
