/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1ServiceImage;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1ServicesImages
 */



public class V1ServicesImages {
  @SerializedName("serviceImages")
  private List<V1ServiceImage> serviceImages = null;

  public V1ServicesImages serviceImages(List<V1ServiceImage> serviceImages) {
    this.serviceImages = serviceImages;
    return this;
  }

  public V1ServicesImages addServiceImagesItem(V1ServiceImage serviceImagesItem) {
    if (this.serviceImages == null) {
      this.serviceImages = new ArrayList<V1ServiceImage>();
    }
    this.serviceImages.add(serviceImagesItem);
    return this;
  }

   /**
   * Get serviceImages
   * @return serviceImages
  **/
  @Schema(description = "")
  public List<V1ServiceImage> getServiceImages() {
    return serviceImages;
  }

  public void setServiceImages(List<V1ServiceImage> serviceImages) {
    this.serviceImages = serviceImages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ServicesImages v1ServicesImages = (V1ServicesImages) o;
    return Objects.equals(this.serviceImages, v1ServicesImages.serviceImages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceImages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ServicesImages {\n");
    
    sb.append("    serviceImages: ").append(toIndentedString(serviceImages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
