/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1SearchFilterConjunctionOperator;
import com.spectrocloud.client.model.V1SearchFilterGroup;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1SearchFilterSpec
 */



public class V1SearchFilterSpec {
  @SerializedName("conjunction")
  private V1SearchFilterConjunctionOperator conjunction = null;

  @SerializedName("filterGroups")
  private List<V1SearchFilterGroup> filterGroups = null;

  public V1SearchFilterSpec conjunction(V1SearchFilterConjunctionOperator conjunction) {
    this.conjunction = conjunction;
    return this;
  }

   /**
   * Get conjunction
   * @return conjunction
  **/
  @Schema(description = "")
  public V1SearchFilterConjunctionOperator getConjunction() {
    return conjunction;
  }

  public void setConjunction(V1SearchFilterConjunctionOperator conjunction) {
    this.conjunction = conjunction;
  }

  public V1SearchFilterSpec filterGroups(List<V1SearchFilterGroup> filterGroups) {
    this.filterGroups = filterGroups;
    return this;
  }

  public V1SearchFilterSpec addFilterGroupsItem(V1SearchFilterGroup filterGroupsItem) {
    if (this.filterGroups == null) {
      this.filterGroups = new ArrayList<V1SearchFilterGroup>();
    }
    this.filterGroups.add(filterGroupsItem);
    return this;
  }

   /**
   * Get filterGroups
   * @return filterGroups
  **/
  @Schema(description = "")
  public List<V1SearchFilterGroup> getFilterGroups() {
    return filterGroups;
  }

  public void setFilterGroups(List<V1SearchFilterGroup> filterGroups) {
    this.filterGroups = filterGroups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1SearchFilterSpec v1SearchFilterSpec = (V1SearchFilterSpec) o;
    return Objects.equals(this.conjunction, v1SearchFilterSpec.conjunction) &&
        Objects.equals(this.filterGroups, v1SearchFilterSpec.filterGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conjunction, filterGroups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1SearchFilterSpec {\n");
    
    sb.append("    conjunction: ").append(toIndentedString(conjunction)).append("\n");
    sb.append("    filterGroups: ").append(toIndentedString(filterGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
