/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1SearchFilterSchemaSpecProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1SearchFilterSchemaSpecProperties
 */



public class V1SearchFilterSchemaSpecProperties {
  @SerializedName("properties")
  private List<V1SearchFilterSchemaSpecProperty> properties = null;

  public V1SearchFilterSchemaSpecProperties properties(List<V1SearchFilterSchemaSpecProperty> properties) {
    this.properties = properties;
    return this;
  }

  public V1SearchFilterSchemaSpecProperties addPropertiesItem(V1SearchFilterSchemaSpecProperty propertiesItem) {
    if (this.properties == null) {
      this.properties = new ArrayList<V1SearchFilterSchemaSpecProperty>();
    }
    this.properties.add(propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @Schema(description = "")
  public List<V1SearchFilterSchemaSpecProperty> getProperties() {
    return properties;
  }

  public void setProperties(List<V1SearchFilterSchemaSpecProperty> properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1SearchFilterSchemaSpecProperties v1SearchFilterSchemaSpecProperties = (V1SearchFilterSchemaSpecProperties) o;
    return Objects.equals(this.properties, v1SearchFilterSchemaSpecProperties.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1SearchFilterSchemaSpecProperties {\n");
    
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
