/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1ClusterConfigEntity;
import com.spectrocloud.client.model.V1SpectroClusterPolicies;
import com.spectrocloud.client.model.V1SpectroClusterProfileEntity;
import com.spectrocloud.client.model.V1VirtualClusterConfig;
import com.spectrocloud.client.model.V1VirtualMachinePoolConfigEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * V1SpectroVirtualClusterEntitySpec
 */



public class V1SpectroVirtualClusterEntitySpec {
  @SerializedName("cloudConfig")
  private V1VirtualClusterConfig cloudConfig = null;

  @SerializedName("clusterConfig")
  private V1ClusterConfigEntity clusterConfig = null;

  @SerializedName("machinepoolconfig")
  private List<V1VirtualMachinePoolConfigEntity> machinepoolconfig = null;

  @SerializedName("policies")
  private V1SpectroClusterPolicies policies = null;

  @SerializedName("profiles")
  private List<V1SpectroClusterProfileEntity> profiles = null;

  public V1SpectroVirtualClusterEntitySpec cloudConfig(V1VirtualClusterConfig cloudConfig) {
    this.cloudConfig = cloudConfig;
    return this;
  }

   /**
   * Get cloudConfig
   * @return cloudConfig
  **/
  @Schema(description = "")
  public V1VirtualClusterConfig getCloudConfig() {
    return cloudConfig;
  }

  public void setCloudConfig(V1VirtualClusterConfig cloudConfig) {
    this.cloudConfig = cloudConfig;
  }

  public V1SpectroVirtualClusterEntitySpec clusterConfig(V1ClusterConfigEntity clusterConfig) {
    this.clusterConfig = clusterConfig;
    return this;
  }

   /**
   * Get clusterConfig
   * @return clusterConfig
  **/
  @Schema(required = true, description = "")
  public V1ClusterConfigEntity getClusterConfig() {
    return clusterConfig;
  }

  public void setClusterConfig(V1ClusterConfigEntity clusterConfig) {
    this.clusterConfig = clusterConfig;
  }

  public V1SpectroVirtualClusterEntitySpec machinepoolconfig(List<V1VirtualMachinePoolConfigEntity> machinepoolconfig) {
    this.machinepoolconfig = machinepoolconfig;
    return this;
  }

  public V1SpectroVirtualClusterEntitySpec addMachinepoolconfigItem(V1VirtualMachinePoolConfigEntity machinepoolconfigItem) {
    if (this.machinepoolconfig == null) {
      this.machinepoolconfig = new ArrayList<V1VirtualMachinePoolConfigEntity>();
    }
    this.machinepoolconfig.add(machinepoolconfigItem);
    return this;
  }

   /**
   * Get machinepoolconfig
   * @return machinepoolconfig
  **/
  @Schema(description = "")
  public List<V1VirtualMachinePoolConfigEntity> getMachinepoolconfig() {
    return machinepoolconfig;
  }

  public void setMachinepoolconfig(List<V1VirtualMachinePoolConfigEntity> machinepoolconfig) {
    this.machinepoolconfig = machinepoolconfig;
  }

  public V1SpectroVirtualClusterEntitySpec policies(V1SpectroClusterPolicies policies) {
    this.policies = policies;
    return this;
  }

   /**
   * Get policies
   * @return policies
  **/
  @Schema(description = "")
  public V1SpectroClusterPolicies getPolicies() {
    return policies;
  }

  public void setPolicies(V1SpectroClusterPolicies policies) {
    this.policies = policies;
  }

  public V1SpectroVirtualClusterEntitySpec profiles(List<V1SpectroClusterProfileEntity> profiles) {
    this.profiles = profiles;
    return this;
  }

  public V1SpectroVirtualClusterEntitySpec addProfilesItem(V1SpectroClusterProfileEntity profilesItem) {
    if (this.profiles == null) {
      this.profiles = new ArrayList<V1SpectroClusterProfileEntity>();
    }
    this.profiles.add(profilesItem);
    return this;
  }

   /**
   * Get profiles
   * @return profiles
  **/
  @Schema(description = "")
  public List<V1SpectroClusterProfileEntity> getProfiles() {
    return profiles;
  }

  public void setProfiles(List<V1SpectroClusterProfileEntity> profiles) {
    this.profiles = profiles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1SpectroVirtualClusterEntitySpec v1SpectroVirtualClusterEntitySpec = (V1SpectroVirtualClusterEntitySpec) o;
    return Objects.equals(this.cloudConfig, v1SpectroVirtualClusterEntitySpec.cloudConfig) &&
        Objects.equals(this.clusterConfig, v1SpectroVirtualClusterEntitySpec.clusterConfig) &&
        Objects.equals(this.machinepoolconfig, v1SpectroVirtualClusterEntitySpec.machinepoolconfig) &&
        Objects.equals(this.policies, v1SpectroVirtualClusterEntitySpec.policies) &&
        Objects.equals(this.profiles, v1SpectroVirtualClusterEntitySpec.profiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cloudConfig, clusterConfig, machinepoolconfig, policies, profiles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1SpectroVirtualClusterEntitySpec {\n");
    
    sb.append("    cloudConfig: ").append(toIndentedString(cloudConfig)).append("\n");
    sb.append("    clusterConfig: ").append(toIndentedString(clusterConfig)).append("\n");
    sb.append("    machinepoolconfig: ").append(toIndentedString(machinepoolconfig)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    profiles: ").append(toIndentedString(profiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
