/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1Upgrades;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Cluster status upgrades
 */
@Schema(description = "Cluster status upgrades")


public class V1SpectroClusterUidUpgrades {
  @SerializedName("upgrades")
  private List<V1Upgrades> upgrades = null;

  public V1SpectroClusterUidUpgrades upgrades(List<V1Upgrades> upgrades) {
    this.upgrades = upgrades;
    return this;
  }

  public V1SpectroClusterUidUpgrades addUpgradesItem(V1Upgrades upgradesItem) {
    if (this.upgrades == null) {
      this.upgrades = new ArrayList<V1Upgrades>();
    }
    this.upgrades.add(upgradesItem);
    return this;
  }

   /**
   * Get upgrades
   * @return upgrades
  **/
  @Schema(description = "")
  public List<V1Upgrades> getUpgrades() {
    return upgrades;
  }

  public void setUpgrades(List<V1Upgrades> upgrades) {
    this.upgrades = upgrades;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1SpectroClusterUidUpgrades v1SpectroClusterUidUpgrades = (V1SpectroClusterUidUpgrades) o;
    return Objects.equals(this.upgrades, v1SpectroClusterUidUpgrades.upgrades);
  }

  @Override
  public int hashCode() {
    return Objects.hash(upgrades);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1SpectroClusterUidUpgrades {\n");
    
    sb.append("    upgrades: ").append(toIndentedString(upgrades)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
