/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Azure storage container organizes a set of blobs, similar to a directory in a file system
 */
@Schema(description = "Azure storage container organizes a set of blobs, similar to a directory in a file system")


public class V1StorageContainer {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  public V1StorageContainer id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Fully qualified resource ID for the resource.
   * @return id
  **/
  @Schema(description = "Fully qualified resource ID for the resource.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public V1StorageContainer name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the resource
   * @return name
  **/
  @Schema(description = "The name of the resource")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public V1StorageContainer type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the resource. E.g. \&quot;Microsoft.Compute/virtualMachines\&quot;
   * @return type
  **/
  @Schema(description = "The type of the resource. E.g. \"Microsoft.Compute/virtualMachines\"")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1StorageContainer v1StorageContainer = (V1StorageContainer) o;
    return Objects.equals(this.id, v1StorageContainer.id) &&
        Objects.equals(this.name, v1StorageContainer.name) &&
        Objects.equals(this.type, v1StorageContainer.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1StorageContainer {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
