/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1SystemSsoAuthSpec;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * system sso config spec
 */
@Schema(description = "system sso config spec")


public class V1SystemSsoSpec {
  @SerializedName("acsUrlRoot")
  private String acsUrlRoot = null;

  @SerializedName("acsUrlScheme")
  private String acsUrlScheme = null;

  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("audienceUrl")
  private String audienceUrl = null;

  @SerializedName("authSpec")
  private V1SystemSsoAuthSpec authSpec = null;

  @SerializedName("entityId")
  private String entityId = null;

  public V1SystemSsoSpec acsUrlRoot(String acsUrlRoot) {
    this.acsUrlRoot = acsUrlRoot;
    return this;
  }

   /**
   * Get acsUrlRoot
   * @return acsUrlRoot
  **/
  @Schema(description = "")
  public String getAcsUrlRoot() {
    return acsUrlRoot;
  }

  public void setAcsUrlRoot(String acsUrlRoot) {
    this.acsUrlRoot = acsUrlRoot;
  }

  public V1SystemSsoSpec acsUrlScheme(String acsUrlScheme) {
    this.acsUrlScheme = acsUrlScheme;
    return this;
  }

   /**
   * Get acsUrlScheme
   * @return acsUrlScheme
  **/
  @Schema(description = "")
  public String getAcsUrlScheme() {
    return acsUrlScheme;
  }

  public void setAcsUrlScheme(String acsUrlScheme) {
    this.acsUrlScheme = acsUrlScheme;
  }

  public V1SystemSsoSpec apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * Get apiVersion
   * @return apiVersion
  **/
  @Schema(description = "")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public V1SystemSsoSpec audienceUrl(String audienceUrl) {
    this.audienceUrl = audienceUrl;
    return this;
  }

   /**
   * Get audienceUrl
   * @return audienceUrl
  **/
  @Schema(description = "")
  public String getAudienceUrl() {
    return audienceUrl;
  }

  public void setAudienceUrl(String audienceUrl) {
    this.audienceUrl = audienceUrl;
  }

  public V1SystemSsoSpec authSpec(V1SystemSsoAuthSpec authSpec) {
    this.authSpec = authSpec;
    return this;
  }

   /**
   * Get authSpec
   * @return authSpec
  **/
  @Schema(description = "")
  public V1SystemSsoAuthSpec getAuthSpec() {
    return authSpec;
  }

  public void setAuthSpec(V1SystemSsoAuthSpec authSpec) {
    this.authSpec = authSpec;
  }

  public V1SystemSsoSpec entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @Schema(description = "")
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1SystemSsoSpec v1SystemSsoSpec = (V1SystemSsoSpec) o;
    return Objects.equals(this.acsUrlRoot, v1SystemSsoSpec.acsUrlRoot) &&
        Objects.equals(this.acsUrlScheme, v1SystemSsoSpec.acsUrlScheme) &&
        Objects.equals(this.apiVersion, v1SystemSsoSpec.apiVersion) &&
        Objects.equals(this.audienceUrl, v1SystemSsoSpec.audienceUrl) &&
        Objects.equals(this.authSpec, v1SystemSsoSpec.authSpec) &&
        Objects.equals(this.entityId, v1SystemSsoSpec.entityId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acsUrlRoot, acsUrlScheme, apiVersion, audienceUrl, authSpec, entityId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1SystemSsoSpec {\n");
    
    sb.append("    acsUrlRoot: ").append(toIndentedString(acsUrlRoot)).append("\n");
    sb.append("    acsUrlScheme: ").append(toIndentedString(acsUrlScheme)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    audienceUrl: ").append(toIndentedString(audienceUrl)).append("\n");
    sb.append("    authSpec: ").append(toIndentedString(authSpec)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
