/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.spectrocloud.client.model.V1TenantResourceLimit;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Tenant resource limits
 */
@Schema(description = "Tenant resource limits")


public class V1TenantResourceLimits {
  @SerializedName("resources")
  private List<V1TenantResourceLimit> resources = null;

  public V1TenantResourceLimits resources(List<V1TenantResourceLimit> resources) {
    this.resources = resources;
    return this;
  }

  public V1TenantResourceLimits addResourcesItem(V1TenantResourceLimit resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<V1TenantResourceLimit>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @Schema(description = "")
  public List<V1TenantResourceLimit> getResources() {
    return resources;
  }

  public void setResources(List<V1TenantResourceLimit> resources) {
    this.resources = resources;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1TenantResourceLimits v1TenantResourceLimits = (V1TenantResourceLimits) o;
    return Objects.equals(this.resources, v1TenantResourceLimits.resources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resources);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1TenantResourceLimits {\n");
    
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
