/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * If set, EFI will be used instead of BIOS.
 */
@Schema(description = "If set, EFI will be used instead of BIOS.")


public class V1VmEFI {
  @SerializedName("secureBoot")
  private Boolean secureBoot = null;

  public V1VmEFI secureBoot(Boolean secureBoot) {
    this.secureBoot = secureBoot;
    return this;
  }

   /**
   * If set, SecureBoot will be enabled and the OVMF roms will be swapped for SecureBoot-enabled ones. Requires SMM to be enabled. Defaults to true
   * @return secureBoot
  **/
  @Schema(description = "If set, SecureBoot will be enabled and the OVMF roms will be swapped for SecureBoot-enabled ones. Requires SMM to be enabled. Defaults to true")
  public Boolean isSecureBoot() {
    return secureBoot;
  }

  public void setSecureBoot(Boolean secureBoot) {
    this.secureBoot = secureBoot;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1VmEFI v1VmEFI = (V1VmEFI) o;
    return Objects.equals(this.secureBoot, v1VmEFI.secureBoot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secureBoot);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1VmEFI {\n");
    
    sb.append("    secureBoot: ").append(toIndentedString(secureBoot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
