/*
 * Palette APIs - 3.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spectrocloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * V1VmFeatureApiC
 */



public class V1VmFeatureApiC {
  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("endOfInterrupt")
  private Boolean endOfInterrupt = null;

  public V1VmFeatureApiC enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true.
   * @return enabled
  **/
  @Schema(description = "Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true.")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public V1VmFeatureApiC endOfInterrupt(Boolean endOfInterrupt) {
    this.endOfInterrupt = endOfInterrupt;
    return this;
  }

   /**
   * EndOfInterrupt enables the end of interrupt notification in the guest. Defaults to false.
   * @return endOfInterrupt
  **/
  @Schema(description = "EndOfInterrupt enables the end of interrupt notification in the guest. Defaults to false.")
  public Boolean isEndOfInterrupt() {
    return endOfInterrupt;
  }

  public void setEndOfInterrupt(Boolean endOfInterrupt) {
    this.endOfInterrupt = endOfInterrupt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1VmFeatureApiC v1VmFeatureApiC = (V1VmFeatureApiC) o;
    return Objects.equals(this.enabled, v1VmFeatureApiC.enabled) &&
        Objects.equals(this.endOfInterrupt, v1VmFeatureApiC.endOfInterrupt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, endOfInterrupt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1VmFeatureApiC {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    endOfInterrupt: ").append(toIndentedString(endOfInterrupt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
